### ISSUE TITLE
Add :append option to core.spit function

### ISSUE THREAD

**Issue by russtoku** [Olical/nfnl#14]
It would be nice to have an option for the `core.spit` function like the *Clojure* [`spit`](https://clojuredocs.org/clojure.core/spit) function. This would accomodate appending to a file for logging or other purposes.

**Comment by Olical** [comment]
Merged! Thanks a lot, cool addition, going to add some tests too since I didn't have them for spit or slurp yet.

**Comment by Olical** [comment]
Tests added, looking good!
