### ISSUE TITLE
cannot compile macros that contain vim namespace

### ISSUE THREAD

**Issue by katawful** [Olical/nfnl#27]
Some of my macros contain various vim namespace functions used to simplify the macro signature:

```fennel
; this is *not* a macro, it used in macros
(fn scope [opt]
  "Get the scope of an option"
  (let [opt# (tostring opt)]
      (. (vim.api.nvim_get_option_info2 opt# {}) :scope)))
```

these do not compile with nfnl, saying that `vim` is an unknown identifier.

.nfnl.fnl file
```fennel
{:source-file-patterns ["test/fnl/**/*.fnl"
                        "fnl/**/*.fnl"]}
```

the macros are imported with `import-macros` for the file i am attempting to compile

**Comment by Olical** [comment]
So this is actually a vanilla Fennel compiler thing that Aniseed insulated people from by making some large Assumptions for everyone. Those assumptions could cause issues for others, so now I leave everything in the Fennel compiler as default and let you choose if you want to make these changes.

You're running into the compiler sandbox I think, something that prevents you from referring to things that aren't good known global values at compiler / macro time. You can either but `_G.` in front of each of them _or_ disable these checks with one of these options in your `.nfnl.fnl`. I can't remember which one it is in this situation so you might have to try one and then the other (from the [Fennel API docs](https://github.com/bakpakin/Fennel/blob/main/api.md#fennels-lua-api)):

```fennel
{:compiler-options {:allowedGlobals ["vim"] ;; or just false to disable checks
                    :compilerEnv _G}}
```

**Comment by Olical** [comment]
There may be an argument to be made here to change the default `:allowedGlobals` to `["vim"]` if that works for you. And maybe add some more things we know exist in the Neovim ecosystem. I suspect however it's because you're reaching outside of the compiler environment / sandbox without a `_G.` prefix or `:compilerEnv` not being disabled.

One of these should fix the issue I hope!

**Comment by katawful** [comment]
setting `:compilerEnv` to `_G` seems to work just fine, the function gets fired as it should during compilation. might be good to mention this in the docs

**Comment by Olical** [comment]
Yay! I hope the readme updates are helpful too 😄

**Comment by katawful** [comment]
looks good, thanks!
