### ISSUE TITLE
config.default: `nfnl/config.lua:27: bad argument #1 to 'sub' (string expected, got nil)` 

### ISSUE THREAD

**Issue by Kamholtz** [Olical/nfnl#30]
# Problem

The following exception occurs when `(config.default)` is called while `cwd` is a path without an ancestor containing a `.nfnl.fnl` file.

```
; .../nvim-data/lazy/nfnl/lua/nfnl/config.lua:27: bad argument #1 to 'sub' (string expected, got nil)
```

# PR

#29 handles prevents `string.sub` being called with `nil`, resulting in the default case of `(vim.fn.getcwd)`

**Comment by Olical** [comment]
Thanks for fixing this!
