### ISSUE TITLE
"Auto compile on save" not working after commit 596c1a2 on Windows.

### ISSUE THREAD

**Issue by UnderCooled** [Olical/nfnl#31]
`compile.into-file` called with these arguments:
```
root-dir: D:\dev_env\vimconf\nvim
ev.file: rc\dap.fnl
(fs.full-path ev.file): D:\dev_env\vimconf\nvim\fnl\rc\dap.fnl
```

My .nfnl.fnl:
```fennel
{:source-file-patterns ["fnl/**/*.fnl" "fnl/*.fnl" "*.fnl"]
 :compiler-options {:compilerEnv _G}}
```

Is this commit means users should write `source-file-patterns` in Lua's regex now?
```fennel
(core.some #(string.find path $) (cfg [:source-file-patterns]))
```

**Comment by Olical** [comment]
Sorry about this but thanks for the great report! I'll get on this ASAP!

**Comment by Olical** [comment]
> Is this commit means users should write source-file-patterns in Lua's regex now?

This was a mistake and I'm reverting it, I realised the patterns were not being applied in one codepath and applied them as Lua patterns (regexes) which is wrong. You're right, it should just be glob patterns, not Lua patterns (which are a form of regex, but not identical).

**Comment by Olical** [comment]
I'm updating it so it matches against glob patterns as it always should've done. Thank you for the report, you caught a nasty bug I introduced while fixing an issue.

**Comment by Olical** [comment]
Should all be fixed! I've kept my change so as to fix the original issue (things were being compiled when they were not in the source-file-patterns list!) but fixed that change so it treats the patterns as glob patterns, not Lua string match patterns.

**Comment by Olical** [comment]
Although the test for this is failing right now I think the behaviour is fine, so it's _probably_ just the test which I'm trying to fix now. Might have to finish it later though since I'm on the way out.
