### ISSUE TITLE
"Auto comile on save" won't work if I switch window.

### ISSUE THREAD

**Issue by UnderCooled** [Olical/nfnl#32]
For example, I edit autocmd.fnl first, then I split a new window edit colors.fnl.

![image](https://github.com/Olical/nfnl/assets/161503/3c204c43-2a44-4bb9-a494-54767744e0ce)

autocmd.fnl is buffer No.10, colors.fnl is buffer No.16.

Then let's check `:autocmd BufWritePost`:
![image](https://github.com/Olical/nfnl/assets/161503/ab5406c2-52e3-41b9-9e54-555eb0192b20)

So if I jump back to left window(autocmd.fnl), and `:w`, it won't auto compile.

Now if I do a `:e` in left window(autocmd.fnl), let's check `:autocmd BufWritePost`:
![image](https://github.com/Olical/nfnl/assets/161503/2c49519c-f023-4130-94d8-5c56bf877c77)

Now I jump to right window, colors.fnl won't auto compile.

**Comment by Olical** [comment]
Found the issue, I've run into this for a while too, not sure when I introduced it. Thanks for raising this! And again, sorry for the issues, this is still kind of a new project and I can only thank you for running into the things that still aren't right and reporting them to me.

**Comment by Olical** [comment]
Keeping it open until we're both convinced it's fine. This was an issue of autocmd group names clashing and clearing each other.

**Comment by UnderCooled** [comment]
I've updated to latest, It's fine now. 👏

**Comment by Olical** [comment]
Cool! Thanks for confirming! Just chasing down a weird failing test that was revealed after fixing this then I'll close.
