### ISSUE TITLE
Non-alphabetic characters are not allowed in protocol names.

### ISSUE THREAD

**Issue by ttak0422** [Olical/nfnl#35]
When I use ddu-ui I got an error. 
`ddu-ff:/.../.nfnl.fnl is not trusted, refusing to compile.`

I think there are other cases involving non-alphabetic letters.

## related issue
- https://github.com/Olical/nfnl/issues/3

**Comment by Olical** [comment]
Thanks for reporting, what happens if you go into the `.nfnl.fnl` file it's talking about and execute `:trust` inside Neovim? Does the error go away?

**Comment by Olical** [comment]
Also are you getting this error when you write a Fennel file or just by browsing things?

**Comment by ttak0422** [comment]
No problem in normal coding.
In this case, the error occurs in the preview view using fuzzy finder.
Thank you.
![image](https://github.com/Olical/nfnl/assets/15827817/a2290694-b501-483e-a8e0-2519b4ec9c25)

**Comment by Olical** [comment]
Sorry, should've done this ages ago, just had a LOT going on. I've widened my ignore rule so now I ignore this pattern `^[%w-]:/` which includes the fugitive paths I originally cared about as well as these ddu-ui ones.

I worry that it'll break support for things like `ftp` protocols that some people might be using, but maybe I can use an allowlist for the ones that are valid.

I still don't know why this is an issue, you should only see this error if you try to write a file, so I presume something in this plugin is writing a temp file somewhere which is triggering nfnl when it shouldn't. But I can't be sure, so let's use a broad fix for now and move on.

And if you no longer use nfnl so it's a non-issue, no problem! At least this will hopefully be fixed for others in the future.

**Comment by ttak0422** [comment]
Thank you so much.  I love this plugin.
Shouldn't the regular expression here be set like `^[%w-]+:/`?
https://github.com/Olical/nfnl/blob/a7b08d2e828338b45ba69f6a3797e80f755efe9a/fnl/nfnl/callback.fnl#L35

**Comment by Olical** [comment]
You are 1000% correct, fixing now. Thanks!

**Comment by Olical** [comment]
Fixed! Should've written a test for it, will do that now.

**Comment by Olical** [comment]
If you're happy, please feel free to close this 😄 I've extracted the logic and tested it now too.

**Comment by ttak0422** [comment]
It worked perfectly! Thank you!!!
