### ISSUE TITLE
"tried to reference a special form without calling it" on `(set (. …))`

### ISSUE THREAD

**Issue by CosmicToast** [Olical/nfnl#43]
I'm porting my neovim config to fennel (I'm about 8 months past due to do so).
I'm trying to make my mixed tables (e.g `{1; 2; a = 3, b = 4}`) slightly more efficient by implementing them in such a way that the internal lua VM will keep the sequential parts in an array (rather than the typical sparse table approach).

One part of this was writing my own assoc. Here's what I have:
```fennel
(fn assoc [?t ...]
  "Sets the key `k` in table `t` to the value `v`.
   Accepts an arbitrary amount of `k` and `v` pairs.
   Returns the mutated table `t`."
  (let [t (or ?t {})
        lt (inc (length t)) ; for numerical keys
        [k v & xs] [...]]
   (case k
    nil nil
    (where k (and (number? k) (> lt k))) (set (. t k) v)
    (where k (and (number? k) (= k lt))) (table.insert t k v)
    _ (tset t k v))
   (case (length xs)
    0 t
    1 (error "assoc expects even number of arguments after table, found odd number")
    _ (assoc t (table.unpack xs)))))
```

This works as expected in my local fennel, but errors out under nfnl with the error "tried to reference a special form without calling it" referring to the `.` in `(set (. t k) v)`.
If I change this to `(tset t k v)` this works, but kind of loses the point of what I was trying to do.

My best guess (without digging in deeper) is that this is related to the outdated fennel version in the repository (the vendored version is 1.3). I'm not making this the issue title because I haven't *confirmed* it to be the issue.

Would it be possible to update the bundled fennel version to the latest (1.5)?

**Comment by Olical** [comment]
You're probably right and I think it's worth trying this first, nfnl doesn't do anything special to the compiler so any issues with compilation with nfnl specifically are probably version related.

Sorry about falling behind on Fennel updates! I'm usually pretty good with that but have been out of the loop for a little bit. We're now on 1.5.0 and I've re-compiled nfnl itself using the new version, everything seems to work okay and I see no breaking changes in the changelog so hopefully we're all good!

Let me know if this helps or if you run into further issues.

**Comment by CosmicToast** [comment]
That resolved it, thanks!
No worries re: keeping up with upstream versions, I know how it is :)
